name: Run Unit Tests on Individual Python Source Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pygame
        run: python3 -m pip install pygame
      - name: chunk.py
        run: cd src && python3 chunk.py
      - name: gameboard.py
        run: cd src && python3 gameboard.py
      - name: gameobject.py
        run: cd src && python3 gameobject.py
      - name: player.py
        run: cd src && python3 player.py
      
